#include <iostream>

/*
*   Each new term in the Fibonacci sequence is generated by adding the previous two terms.
*   By starting with 1 and 2, the first 10 terms will be:
*   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*   
*   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
* 
*   Answer: 4613732
*/

void func(const uint32_t limit)
{
    uint32_t sum = 0;

    for (uint32_t p1 = 0, p2 = 1, p3 = 1; p3 < limit; p1 = p2, p2 = p3, p3 = p1 + p2)
        if (p3 % 2 == 0) 
            sum += p3;
    

    std::cout << sum << std::endl;
}

int main()
{
    constexpr uint32_t limit = 4'000'000;

    func(limit);

    return 0;
}